# Generated by Django 5.2 on 2025-06-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=200)),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série')], max_length=10)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_temporadas', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_episodios', models.PositiveIntegerField(blank=True, null=True)),
                ('diretor', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.genero')),
            ],
        ),
    ]
