# Generated by Django 5.2 on 2025-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='obras/fotos'),
        ),
    ]
