# Generated by Django 5.2 on 2025-06-20 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='created',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='content',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='object_id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
            preserve_default=False,
        ),
    ]
